// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: Net_Message.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoginResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//  Msg_ID.Msg_LoginRequest id=1;
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginResquest) Reset() {
	*x = LoginResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResquest) ProtoMessage() {}

func (x *LoginResquest) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResquest.ProtoReflect.Descriptor instead.
func (*LoginResquest) Descriptor() ([]byte, []int) {
	return file_Net_Message_proto_rawDescGZIP(), []int{0}
}

func (x *LoginResquest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResquest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid uint32 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_Net_Message_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var file_Net_Message_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*ServerMsg_ID)(nil),
		Field:         2010,
		Name:          "Msg.serverMsgID",
		Tag:           "varint,2010,opt,name=serverMsgID,enum=Msg.ServerMsg_ID",
		Filename:      "Net_Message.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// optional Msg.ServerMsg_ID serverMsgID = 2010;
	E_ServerMsgID = &file_Net_Message_proto_extTypes[0]
)

var File_Net_Message_proto protoreflect.FileDescriptor

var file_Net_Message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4e, 0x65, 0x74, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x4d, 0x73, 0x67, 0x5f, 0x49, 0x44,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x43, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x3a, 0x04, 0xd0, 0x7d, 0x92, 0x4e, 0x3a, 0x55, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xda, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x4d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x5f, 0x49, 0x44,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x42, 0x19, 0x5a,
	0x17, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Net_Message_proto_rawDescOnce sync.Once
	file_Net_Message_proto_rawDescData = file_Net_Message_proto_rawDesc
)

func file_Net_Message_proto_rawDescGZIP() []byte {
	file_Net_Message_proto_rawDescOnce.Do(func() {
		file_Net_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Net_Message_proto_rawDescData)
	})
	return file_Net_Message_proto_rawDescData
}

var file_Net_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Net_Message_proto_goTypes = []interface{}{
	(*LoginResquest)(nil),             // 0: Msg.LoginResquest
	(*LoginResponse)(nil),             // 1: Msg.LoginResponse
	(*descriptor.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(ServerMsg_ID)(0),                 // 3: Msg.ServerMsg_ID
}
var file_Net_Message_proto_depIdxs = []int32{
	2, // 0: Msg.serverMsgID:extendee -> google.protobuf.MessageOptions
	3, // 1: Msg.serverMsgID:type_name -> Msg.ServerMsg_ID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Net_Message_proto_init() }
func file_Net_Message_proto_init() {
	if File_Net_Message_proto != nil {
		return
	}
	file_Msg_ID_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Net_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Net_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_Net_Message_proto_goTypes,
		DependencyIndexes: file_Net_Message_proto_depIdxs,
		MessageInfos:      file_Net_Message_proto_msgTypes,
		ExtensionInfos:    file_Net_Message_proto_extTypes,
	}.Build()
	File_Net_Message_proto = out.File
	file_Net_Message_proto_rawDesc = nil
	file_Net_Message_proto_goTypes = nil
	file_Net_Message_proto_depIdxs = nil
}
