// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: Msg_ID.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServerMsg_ID int32

const (
	ServerMsg_ID_Msg_Null ServerMsg_ID = 0
	//longin消息
	ServerMsg_ID_Msg_LoginRequest  ServerMsg_ID = 10001 //登陆请求
	ServerMsg_ID_Msg_LoginResponse ServerMsg_ID = 10002 //登陆返回
	ServerMsg_ID_Msg_LoginRegist   ServerMsg_ID = 10003 //注册请求
)

// Enum value maps for ServerMsg_ID.
var (
	ServerMsg_ID_name = map[int32]string{
		0:     "Msg_Null",
		10001: "Msg_LoginRequest",
		10002: "Msg_LoginResponse",
		10003: "Msg_LoginRegist",
	}
	ServerMsg_ID_value = map[string]int32{
		"Msg_Null":          0,
		"Msg_LoginRequest":  10001,
		"Msg_LoginResponse": 10002,
		"Msg_LoginRegist":   10003,
	}
)

func (x ServerMsg_ID) Enum() *ServerMsg_ID {
	p := new(ServerMsg_ID)
	*p = x
	return p
}

func (x ServerMsg_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMsg_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_Msg_ID_proto_enumTypes[0].Descriptor()
}

func (ServerMsg_ID) Type() protoreflect.EnumType {
	return &file_Msg_ID_proto_enumTypes[0]
}

func (x ServerMsg_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMsg_ID.Descriptor instead.
func (ServerMsg_ID) EnumDescriptor() ([]byte, []int) {
	return file_Msg_ID_proto_rawDescGZIP(), []int{0}
}

var File_Msg_ID_proto protoreflect.FileDescriptor

var file_Msg_ID_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x5f, 0x49, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x4d, 0x73, 0x67, 0x2a, 0x61, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x5f, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x5f, 0x4e, 0x75, 0x6c, 0x6c, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x91, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x5f,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x92, 0x4e,
	0x12, 0x14, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x10, 0x93, 0x4e, 0x42, 0x19, 0x5a, 0x17, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Msg_ID_proto_rawDescOnce sync.Once
	file_Msg_ID_proto_rawDescData = file_Msg_ID_proto_rawDesc
)

func file_Msg_ID_proto_rawDescGZIP() []byte {
	file_Msg_ID_proto_rawDescOnce.Do(func() {
		file_Msg_ID_proto_rawDescData = protoimpl.X.CompressGZIP(file_Msg_ID_proto_rawDescData)
	})
	return file_Msg_ID_proto_rawDescData
}

var file_Msg_ID_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Msg_ID_proto_goTypes = []interface{}{
	(ServerMsg_ID)(0), // 0: Msg.ServerMsg_ID
}
var file_Msg_ID_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Msg_ID_proto_init() }
func file_Msg_ID_proto_init() {
	if File_Msg_ID_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Msg_ID_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Msg_ID_proto_goTypes,
		DependencyIndexes: file_Msg_ID_proto_depIdxs,
		EnumInfos:         file_Msg_ID_proto_enumTypes,
	}.Build()
	File_Msg_ID_proto = out.File
	file_Msg_ID_proto_rawDesc = nil
	file_Msg_ID_proto_goTypes = nil
	file_Msg_ID_proto_depIdxs = nil
}
